### ISSUE TITLE
Setup: "undefined function: :eleveldb.open/2 (module :eleveldb is not available)"

### ISSUE THREAD

**Issue by awenger** [skovsgaard/exleveldb#11]
Sorry, I guess it's my inexperience with elixir and mix but I don't get exleveldb working.
I created a new project with mix and added exleveldb. mix.exs:
```
  defp deps do
    [{ :exleveldb,   "~> 0.5.0"} ]
  end
```
I ran ```mix do deps.get, deps.compile``` in my project dir. But opening a db causes the following error:
```
{:ok, testdb} = Exleveldb.open("/tmp/test/db", [{:create_if_missing, :true}])
-----
** (UndefinedFunctionError) undefined function: :eleveldb.open/2 (module :eleveldb is not available)
              :eleveldb.open('/tmp/test/db', [create_if_missing: true])
    (test) lib/test.ex:5: Test.test/0
```

I also tried to run ```mix do deps.get, deps.compile``` in ```deps/exleveldb/```. Furthermore ```mix test``` in ```deps/exleveldb``` shows:
```
Finished in 0.4 seconds (0.1s on load, 0.3s on tests)
11 tests, 0 failures

Randomized with seed 179804
```
The previous command also creates a new database (```/tmp/test/db```) if I execute it in the ```deps/exleveldb/``` dir.

Did I miss something?

**Comment by skovsgaard** [comment]
Sorry it's taking a second but I will look into this ASAP. If you've run deps.get in both directories, I can't see the issue off the top of my head, so I'll have to test it manually (and write new tests to cover this).

I'll get back to you soon as I have a second to check it out.

**Comment by skovsgaard** [comment]
Okay, so tests are still work in progress, but the issue you were having is fixed now. I wasn't explicitly asking for v2.1.0 of eleveldb in my deps.

Now `mix do deps.get, deps.compile` should work without you needing to install anything from within the dependency directory.

Thanks for bringing it up and let me know if you have any other issues :)
