### ISSUE TITLE
erratical fold and fold_key test cases error

### ISSUE THREAD

**Issue by oscarftoro** [skovsgaard/exleveldb#4]
When running mix test, sporadically, the following test cases fail:

 1) test it's possible to iterate over the keys of the currently open datastore (ExleveldbTest)
     test/exleveldb_test.exs:59
     ** (ArgumentError) argument error
     stacktrace:
       (eleveldb) :eleveldb.async_iterator_close(#Reference<0.0.0.1042>, "")
       (eleveldb) src/eleveldb.erl:215: :eleveldb.iterator_close/1
       (eleveldb) src/eleveldb.erl:338: :eleveldb.do_fold/4
       test/exleveldb_test.exs:69

.

  2) test it's possible to iterate over the key-value pairs in the currently open datastore (ExleveldbTest)
     test/exleveldb_test.exs:46
     ** (ArgumentError) argument error
     stacktrace:
       (eleveldb) :eleveldb.async_iterator_close(#Reference<0.0.0.1063>, "")
       (eleveldb) src/eleveldb.erl:215: :eleveldb.iterator_close/1
       (eleveldb) src/eleveldb.erl:338: :eleveldb.do_fold/4
       test/exleveldb_test.exs:56

Have you experienced the same?

**Comment by skovsgaard** [comment]
This is happening for me too as of v0.5.0. However only when running a `mix test` on a clean project.

All tests are passing past the first run, so I assume it's a problem in how (or really when) the datastore is being created for the fold tests.

**Comment by skovsgaard** [comment]
Kinda parked for now. The idea is to refactor the tests altogether, which should also cover the weird side effect issues.
